[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "Safe Network Client"
documentation = "https://docs.rs/sn_client"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_client"
readme = "README.md"
repository = "https://github.com/maidsafe/sn_client"
version = "0.44.5"
keywords = [ "Safe", "Network", "SafeNetwork" ]

[package.metadata.docs.rs]
features = [ "simulated-payouts" ]

[dependencies]
async-trait = "~0.1.41"
bincode = "1.2.1"
dirs-next = "1.0.1"
futures = "~0.3.5"
futures-util = "~0.3.4"
env_logger = "~0.6.2"
lazy_static = "1.4.0"
log = "~0.4.8"
lru = "~0.5.1"
qp2p = "~0.9.3"
rand = "~0.7.3"
regex = "1.3.1"
# sn_data_types = "~0.11.36"
sn_data_types = { git = "https://github.com/oetyng/sn_data_types", branch = "refactor-chunk-duplication" }
sn_transfers = { git = "https://github.com/oetyng/sn_transfers", branch = "refactor-chunk-duplication" }
# sn_transfers = "~0.2.4"
# sn_transfers = { path = "../sn_transfers" }
self_encryption = "~0.19.4"
serde_json = "1.0.53"
serde-value = "~0.5.3"
sha3 = "~0.8.2"
tiny-keccak = "1.5.0"
threshold_crypto = "0.4.0"
unwrap = "1.2.0"
url = "2.1.0"
ws = "~0.9.1"
crdts = "~4.3.0"
xor_name = "1.1.3"

  [dependencies.bytes]
  version = "~0.5.4"
  features = [ "serde" ]

  [dependencies.chrono]
  version = "~0.4.0"
  features = [ "serde" ]

  [dependencies.log4rs]
  version = "~0.8.3"
  features = [ "toml_format" ]

  [dependencies.miscreant]
  version = "~0.4.2"
  features = [ "soft-aes" ]

  [dependencies.serde]
  version = "1.0.111"
  features = [ "derive", "rc" ]

  [dependencies.tokio]
  version = "~0.2.21"
  features = [ "rt-core", "blocking", "stream", "rt-util" ]

[dev-dependencies]
serde_json = "1.0.9"

[features]
simulated-payouts = [
  "sn_data_types/simulated-payouts",
  "sn_transfers/simulated-payouts"
]
testing = [ ]

